### PR TITLE
feat: add wallet structure and basic commands

### PR DESCRIPTION
**Pull request by NathanInnes**
## Description

WIP...

## Test Results
image

### CODE REVIEW

**Comment by kiwi2021** [comment]
This does not have approval from Mod/Admin team. Discuss in Discord Bot channel before continuing.

**Comment by NathanInnes** [comment]
> This does not have approval from Mod/Admin team. Discuss in Discord Bot channel before continuing.

I'm aware that this is up for discussion. I've told Ben to post a message in mod channel regarding this.

**Comment by NathanInnes** [comment]
> How does this benefit the FBW community?

Depends how you look at it. The idea is a small currency based system to play mini-games with the bot.

In terms of do we need it... absolutely not but theres a lot of things that this bot does that isn't essential. Just for fun

**Comment by Lucky38i** [comment]
> > How does this benefit the FBW community?
> 
> Depends how you look at it. The idea is a small currency based system to play mini-games with the bot.
> 
> In terms of do we need it... absolutely not but theres a lot of things that this bot does that isn't essential. Just for fun

Majority of the commands are split between memes and support. I don't see this fitting in either of these section, this command looks very useful in a more gaming central server but I don't really see it's fit here.

**Comment by NathanInnes** [comment]
> Majority of the commands are split between memes and support. I don't see this fitting in either of these section, this command looks very useful in a more gaming central server but I don't really see it's fit here.

In terms of category I'm awaiting the rename directory or to be merged. Discussion is discord channel about taking another approach to this that I will work on tonight.

**Comment by NathanInnes** [comment]
Closing and will reopen a new PR that is restructured.

**Pull request closed without merging**
