### PR TITLE
feat: TOD estimate calculator

### PR DESCRIPTION
**Pull request by NakajimaYoshi**
feat: Estimated TOD Calculator

Uses the [rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(aeronautics)) to provide an estimation of Top of Descent with a 3 degree flight path. Supports raw altitude as well as flight levels.
## Test Results

image

## Discord Username
HowNowBrownCrow#2591

### CODE REVIEW

**Comment by NakajimaYoshi** [comment]
image

**Comment by NakajimaYoshi** [comment]
image

**Comment by NakajimaYoshi** [comment]
image

**Comment by benw202** [comment]
Please reference #223 and add your command to the changelog and commands list when it is ready for review :)

**Pull request closed without merging**
