### PR TITLE
fix: mentions in various commands

### PR DESCRIPTION
**Pull request by benw202**
## Description

Fixes mentions in multiple commands

## Test Results

Old:
image

New:
image

## Discord Username

BenW#8484

### CODE REVIEW

**Comment by NathanInnes** [comment]
There are a good few files that could also be updated. Do you wish to add them to this PR also or just keep what is here?

**Comment by benw202** [comment]
> There are a good few files that could also be updated. Do you wish to add them to this PR also or just keep what is here?

Ahh, do they also contain the error, or do they work but have it done the other way?

**Comment by benw202** [comment]
@NathanInnes, do I have them all or did you spot some more? I am pretty sure they should all work in this configuration unless I have missed any!

**Comment by NathanInnes** [comment]
A quick search found 12 cases. Does this also affect the channels and users roles? Not checked personally.
image

**Comment by benw202** [comment]
It doesn't affect the channels and users roles.

`<@${msg.author.id}` does work correctly, as here we are grabbing the id, and adding the @$ so that the client sees it as a tag.

If we are not grabbing an id, or using .tag I think thats where we need to change it, as something changed with this due to the upgrade. I will go through files with mentions and test them all.

**Comment by NathanInnes** [comment]
After testing, it is not necessary to wrap <@> around mentions for users. Roles and channels must be wrapped as they must be resolved first. This can be overcome with the use of a helper function if we wish to clean it up for maintainability in future.

**Comment by NathanInnes** [comment]
Affected files:
- whois
- messageDelete
- ban
- timeout
- untimeout
- Possibly warns? (Depends if user has been resolved)
- deleteWarn
- help
- scamlog

**Review by NathanInnes — APPROVED** [review]

**Pull request merged**
