### PR TITLE
feat: marketplace removal command

### PR DESCRIPTION
**Pull request by ImenesFBW**
## Description

Provides help with removing the marketplace version.

## Test Results

image

## Discord Username

Imenes#0320

### CODE REVIEW

**Comment by benw202** [comment]
Is it worth adding a couple of aliases? `marketremove`,  `removemarket` and so on?

**Review by NathanInnes — CHANGES_REQUESTED** [review]

**Comment by ImenesFBW** [comment]
> Is it worth adding a couple of aliases? `marketremove`,  `removemarket` and so on?

Not sure, your call. Was thinking about it but the seemed like long commands. Can throw them in if you think it would be handy.

**Comment by benw202** [comment]
> > Is it worth adding a couple of aliases? `marketremove`,  `removemarket` and so on?
> 
> Not sure, your call. Was thinking about it but they seemed like long commands. Can throw them in if you think it would be handy.

A couple won't hurt. We have some longer command names. Sometimes helps the users who don't read the docs as they can try a more 'plain' command name in the hopes they find what they are looking for.

**Comment by ImenesFBW** [comment]
> > > Is it worth adding a couple of aliases? `marketremove`,  `removemarket` and so on?
> > 
> > Not sure, your call. Was thinking about it but they seemed like long commands. Can throw them in if you think it would be handy.
> 
> A couple won't hurt. We have some longer command names. Sometimes helps the users who don't read the docs as they can try a more 'plain' command name in the hopes they find what they are looking for.

Sounds good will add them when I get back home. The ones you suggested and maybe also .rm and  .mr if not taken or is that too much?

**Review by benw202 — APPROVED** [review]
LGTM! - (Person to merge just needs to update changelog date)

**Comment by ImenesFBW** [comment]
> LGTM! - (Person to merge just needs to update changelog date)

Thanks! I'll keep bumping the date to keep it easy on the guy that will press the big green button.

**Comment by benw202** [comment]
Just tagging on a commit to fix the changelog from previous PR

**Pull request merged**
