### PR TITLE
feat: Wolfram Alpha Command

### PR DESCRIPTION
**Pull request by Zowlyfon**
## Description
This command provides access to the wolfram alpha API.

It requires the environment variable WOLFRAMALPHA_TOKEN to be set to a valid app ID from wolfram alpha.
This is free for non commercial usage, capped at 2000 requests per month.
https://products.wolframalpha.com/api/

## Test Results
I have tested various input, including ones that might cause an issue and they seem to be working well.

fbw_bot_wa_test

## Discord Username
Zowlyfon#5429

### CODE REVIEW

**Comment by NathanInnes** [comment]
Could I suggest that you add extra command prefixes that would be appropriate for this? Maybe ```.ask``` and ```.calculate```

**Comment by Zowlyfon** [comment]
> Could I suggest that you add extra command prefixes that would be appropriate for this? Maybe `.ask` and `.calculate`

Done :)

I've also made a guess at the changes required for deployment, however these require testing.

**Comment by benw202** [comment]
The token will need to be added to the staging and production workflows as well (found under .github/workflows). There are two entries in each file for it, should be self explanatory but message on Discord if you need help!

**Comment by Zowlyfon** [comment]
> The token will need to be added to the staging and production workflows as well (found under .github/workflows). There are two entries in each file for it, should be self explanatory but message on Discord if you need help!

I think I've done that now, let me know if I've done it incorrectly

**Comment by benw202** [comment]
In contributing, it may be worth changing it to something like:

```
### Tokens

Some commands may require additional tokens. If you would like to test them out on your bot, you must include the tokens inside your .env file. These commands include the metar, station and Wolfram Alpha commands. The steps below will explain how to set this up.

#### AVWX (Metar and Station)

1. Make a free account [here](https://avwx.rest/). Then, follow the steps [here](https://account.avwx.rest/getting-started) to get your token
2. Inside the .env file, on a new line type `METAR_TOKEN=TOKEN` replacing TOKEN with what you copied in step 1
3. Then, on another new line within the .env file, type `STATION_TOKEN=TOKEN` replacing TOKEN with what you copied in step 1

#### Wolfram Alpha

1. Select get API access [here](https://products.wolframalpha.com/api/) to create an account.
2. Once you have an account you will need to get an AppID from [here](https://developer.wolframalpha.com/portal/myapps/)
3. Inside the .env file, on a new line type `WOLFRAMALPHA_TOKEN=TOKEN` replacing TOKEN with your wolfram alpha AppID
```

Gives a bit of a clearer separation potentially? Let me know what you think!

**Comment by benw202** [comment]
Liking this! See a few comments on Discord :)

**Comment by oim1** [comment]
lgtm!

**Review by benw202 — APPROVED** [review]
LGTM!

**Pull request merged**
