### PR TITLE
fix: Improve wxr and terr command

### PR DESCRIPTION
**Pull request by tracernz**
## Description

The first paragraph was inaccurate and the short commands were not great (e.g. wxr is much more likely to come to mind than wx).

The reasons we cannot implement even the weather map on the ND are actually, roughly in order of importance:
- the map projection used by the MSFS weather map is different to the ND,
- the image rendering/style cannot be sufficiently customised to match any of the A320 WxR LRUs,
- there is no way to access hazard data for the icons shown by the RDR4000,
- we did have some perf issues in the past but it's unclear whether this would be the case for a new implementation,

An actual weather radar (aside from the ND map) requires even more from the sim.

### CODE REVIEW

**Comment by tracernz** [comment]
Why do we need a changelog for something with git history and no releases to users?

**Comment by benw202** [comment]
> Why do we need a changelog for something with git history and no releases to users?

Thanks for the PR. We use a changelog as an easy way for support members (and anyone who is interested) to see what's happening with our bot. It automatically gets pulled to [FBW docs](https://docs.flybywiresim.com/dev-corner/development-projects/discord-bot/#changelog)

**Review by benw202 — CHANGES_REQUESTED** [review]
Please update `.github/command-docs.md` with the extra aliases you've added.

**Comment by tracernz** [comment]
Don't want to spend any more time on this. If anybody wants to pick it up feel free.

**Comment by benw202** [comment]
Re-opened to complete

**Review by benw202 — APPROVED** [review]

**Pull request merged**
