### PR TITLE
fix: metar units

### PR DESCRIPTION
**Pull request by peregrine-developments**
## Description

Visibility & wind direction previously displayed with units incorrectly. Checks for each have been fixed.

## Test Results

See: CAVOK and VRB
image

## Discord Username

pererry#8489

### CODE REVIEW

**Review by NathanInnes — CHANGES_REQUESTED** [review]
Please add entry to changelog.

**Comment by tracernz** [comment]
Units should always be preceded by spaces. Can we not use unicode? °

**Comment by NathanInnes** [comment]
I suggest possibly doing it like this.

SEE GIST
https://gist.github.com/NathanInnes/c368388a3ab7bd6f67007c8bd56cc54d

**Comment by peregrine-developments** [comment]
extracted units to constants.ts and added a space between value and units for all fields

**Review by NathanInnes — COMMENTED** [review]
Looks great, just need to adjust the changelog though, you've made an entry to May instead of June :P

**Comment by peregrine-developments** [comment]
> Looks great, just need to adjust the changelog though, you've made an entry to May instead of June :P

Man, my internal clock has been off since the start of 2020 😂 I'll fix the merge while I'm at it

**Review by NathanInnes — APPROVED** [review]

**Pull request merged**
