### PR TITLE
feat: add flights command

### PR DESCRIPTION
**Pull request by NathanInnes**
## Description

Adds .flights .liveflights .stats commands to return the current amount of people flying FBW.

Could add more to it and make it just a stats command for FBW if anyone has ideas.

## Test Results
image

## Discord Username
NathanI#8668

### CODE REVIEW

**Comment by benw202** [comment]
I like this!

We could definitely add more to it - or split into 2 commands. Couple ideas below:

Github contribs, downloads, if hours flown is logged?)

**Comment by NathanInnes** [comment]
Hours flown is not logged but rest can be done

**Comment by NathanInnes** [comment]
Going to put this into draft so I can add more stuff and implement node-fetch with it.

**Comment by benw202** [comment]
> Going to put this into draft so I can add more stuff and implement node-fetch with it.

Is node-fetch specific to the flights command only? If not, would prefer a separate PR

**Comment by NathanInnes** [comment]
> > Going to put this into draft so I can add more stuff and implement node-fetch with it.
> 
> Is node-fetch specific to the flights command only? If not, would prefer a separate PR

That's what I am working on right now, looking to migrate everything over to node-fetch instead before continuing this PR.

**Comment by NathanInnes** [comment]
Awaiting #273 before continuing work on this.

**Comment by NathanInnes** [comment]
Closing to reopen a new PR.

**Pull request closed without merging**
