### PR TITLE
docs: changelog refactor

### PR DESCRIPTION
**Pull request by benw202**
## Description

Work in progress

## Discord Username

BenW#8484

### CODE REVIEW

**Comment by NathanInnes** [comment]
Progress on getting this implemented?

**Comment by benw202** [comment]
> Progress on getting this implemented?

Yep, have been busy at work and then on holiday. I will get to it when I can

**Comment by benw202** [comment]
Apologies on the delay for this - is this something we still want to change? Or are we happy with the existing format?

**Comment by benw202** [comment]
@pdellaert - Thoughts? This was requested a while ago - I was personally happy with our changelog format.

**Comment by pdellaert** [comment]
Personally, I don't think a refactor is needed. Having the person mentioned like in the a32nx changelog for attribution is nice, but not a must to me, honestly. And if we want to do that, we can just start doing that now, instead of having to do a whole history (unless it can be automated).

**Comment by NathanInnes** [comment]
The points were to drop <small> tags and unecessary underscore in beginning in favour of just using markdown titles. Names did not have to be done in this PR, but can be done in any future PRs

**Pull request closed without merging**
