### PR TITLE
docs: copy changelog and command listing from docs repo

### PR DESCRIPTION
**Pull request by Valastiri**
## Description

Moves bot documentation from the fbw/docs repo. 

This PR serves 3 purposes:

1. Host changelog and command table locally within the discord-bot repo
2. Allow the docs repo to pull these documents externally
3. Simplifies maintenance of documentation 

## Recommendations

- Keep an H2 initial header for compatibility.
- Possibly adopt A32NX repo style for the CHANGELOG.md

## Test Results

N/A

## Discord Username

Valastiri#8902

### CODE REVIEW

**Comment by NathanInnes** [comment]
Shift the command docs into the .github also :)

**Comment by NathanInnes** [comment]
Instead of doing updates by specific date, I reccommend that updates are cateorgized by month

**Comment by Valastiri** [comment]
> Instead of doing updates by specific date, I reccommend that updates are cateorgized by month

Yea I agree, I'm unsure if we want to merge this document move in first and then streamline it after the fact. I'm sure that there'd need to be some changes to contributing.md.

If this is merged I can just start hosting it on `fbw/docs` and no longer have to maintain it on that repo.

**Comment by benw202** [comment]
> > Instead of doing updates by specific date, I reccommend that updates are cateorgized by month
> 
> Yea I agree, I'm unsure if we want to merge this document move in first and then streamline it after the fact. I'm sure that there'd need to be some changes to contributing.md.
> 
> If this is merged I can just start hosting it on `fbw/docs` and no longer have to maintain it on that repo.

Agree - changes need to be made. It will be ongoing so I will merge this when I am off work tomorrow and then PR changes etc.

**Comment by NathanInnes** [comment]
I have already updated the contributing guide in this PR here [5e72519](https://github.com/flybywiresim/discord-bot/pull/223/commits/5e72519d55108d280845b070176cb500eeca766d).

**Review by benw202 — APPROVED** [review]
LGTM!

**Pull request merged**
